
spring:
  profiles:
    active: dev

---
server:
  port: 8081
spring:
  profiles: dev
  application:
    name: springCloud-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.63.56:3306/bot?
    username: root
    password: root
mybatis:
  config-location: classpath*:mapper/*Dao.xml
eureka:
  client:
    service-url:
      defaultZone: http://39.96.63.56:7894/eureka/
  instance:
    instance-id: springCloud-api-hystrix8081
    prefer-ip-address: true
---
server:
  port: 8082
spring:
  profiles: test
  application:
    name: springCloud-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.63.56:3306/bot?
    username: root
    password: root
mybatis:
  config-location: classpath*:mapper8082/*Dao.xml
eureka:
  client:
    service-url:
      defaultZone: http://39.96.63.56:7894/eureka/
  instance:
    instance-id: springCloud-api-hystrix8082
    prefer-ip-address: true
